.PHONY: clean All

All:
	@echo "----------Building project:[ helloENV - Debug ]----------"
	@cd "helloENV" && $(MAKE) -f  "helloENV.mk"
clean:
	@echo "----------Cleaning project:[ helloENV - Debug ]----------"
	@cd "helloENV" && $(MAKE) -f  "helloENV.mk" clean
