.PHONY: clean All

All:
	@echo "----------Building project:[ helloWorld - Debug ]----------"
	@$(MAKE) -f  "helloWorld.mk"
clean:
	@echo "----------Cleaning project:[ helloWorld - Debug ]----------"
	@$(MAKE) -f  "helloWorld.mk" clean
